import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { auth, signIn } from "@/auth";
import "./globals.css";
import { SignIn, SignOut } from "./components/Auth";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    console.log("LOADING");
    // console.log(session);

    return (
        <html lang="en">
            <body
                className={`${inter.className} flex flex-col items-center min-h-[100dvh] bg-gradient-to-br from-[#003b95] to-[#5296e3] text-white`}
            >
                <header className="px-4 lg:px-6 h-14 flex items-center justify-between w-full max-w-5xl">
                    <Link
                        href="/"
                        className="flex items-center gap-2"
                        prefetch={false}
                    >
                        <span className="text-2xl font-bold">
                            Booking Academy 🧪
                        </span>
                    </Link>
                    <nav className="hidden lg:flex gap-4 sm:gap-6">
                        {!session?.user ? <SignIn /> : <SignOut />}
                    </nav>
                </header>
                <main>{children}</main>
            </body>
        </html>
    );
}
